name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches:
      - master
    paths:
      - "server/**"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # determine the Github runner
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build server image using the dockerfile
        run: cd server && docker build -t aaronpazm/server .

      - name: Login to Docker
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

      - name: Push image to docker hub
        run: docker push aaronpazm/server

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DIGITAL_OCEAN_ACCESS_TOKEN}}
        run: doctl compute ssh mono-store
