name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches:
      - master
    paths:
      - "server/**"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # determine the Github runner
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build server image using the dockerfile
        run: cd server && docker build -t aaronpazm/server .

      - name: Login to Docker
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

      - name: Push image to docker hub
        run: docker push aaronpazm/server

      - name: SSH into the droplet using ssh action that takes host, key, etc
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.PK}}
          envs: DOCKER_USERNAME, DOCKER_PASSWORD
          script: |
            touch file1.txt
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker pull aaronpazm/server
            docker run -p 3000:3000 aaronpazm/server
            curl http://localhost:3000
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
